services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    tty: true
    volumes:
      - .:/app/
    networks:
      - ntwrk

  redis:
    build:
      context: .
      dockerfile: Dockerfile
      target: redis
    networks:
      - ntwrk

networks:
  ntwrk:
    driver: bridge
